-- SQL Setup Script for GameHub - Robust Version

-- Table for custom app users
CREATE TABLE IF NOT EXISTS app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table for game scores/stats
CREATE TABLE IF NOT EXISTS game_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT REFERENCES app_users(username) ON DELETE CASCADE,
  game_type TEXT NOT NULL,
  score INT DEFAULT 0,
  difficulty TEXT,
  result TEXT,
  lives_remaining INT,
  played_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Admin user
INSERT INTO app_users (username, password, role)
VALUES ('Antonio', 'Asd123', 'admin')
ON CONFLICT (username) DO NOTHING;

-- Enable RLS
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_stats ENABLE ROW LEVEL SECURITY;

-- Safe Policy Creation
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'app_users' AND policyname = 'Allow public access'
    ) THEN
        CREATE POLICY "Allow public access" ON app_users FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'game_stats' AND policyname = 'Allow public access stats'
    ) THEN
        CREATE POLICY "Allow public access stats" ON game_stats FOR ALL USING (true);
    END IF;
END
$$;
