-- SQL Setup Script for GameHub

-- Table for custom app users (non-supabase-auth for now)
CREATE TABLE IF NOT EXISTS app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'user', -- 'admin' or 'user'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table for game scores/stats
CREATE TABLE IF NOT EXISTS game_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT REFERENCES app_users(username) ON DELETE CASCADE,
  game_type TEXT NOT NULL, -- 'chess', 'sudoku', etc.
  score INT DEFAULT 0,
  difficulty TEXT, -- 'easy', 'medium', 'hard'
  result TEXT, -- 'win', 'loss', 'draw'
  lives_remaining INT,
  played_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Admin user
INSERT INTO app_users (username, password, role)
VALUES ('Antonio', 'Asd123', 'admin')
ON CONFLICT (username) DO NOTHING;

-- Enable RLS
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_stats ENABLE ROW LEVEL SECURITY;

-- Simple policies for non-auth setup (using service role or public for this specific request)
CREATE POLICY "Allow public access" ON app_users FOR ALL USING (true);
CREATE POLICY "Allow public access stats" ON game_stats FOR ALL USING (true);
